@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor client
boundary post_domain
control post_handler
control post_usecase
database post_repo

client -> post_domain: GET /post
post_domain -> post_handler: getAll()
post_handler -> post_usecase: GetAll()
post_usecase -> post_repo: GetAll()
post_repo --> post_usecase: []domain.Post{}
post_usecase --> post_handler: []domain.Post{}
post_handler --> post_domain: response.GetAll{}
post_domain --> client: JSON
@enduml